Refactored mail service
feather-framework/feather-mail pull request #4
Opened 2023-12-01 13:29 UTC by mzpx

- fixed for service builder protocol
- added new tests

2023-12-01 15:15 UTC, tib requested changes

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTFeatherMailTests.swift
> +            XCTAssert(false, "no exception")
We should use XCTFail("Test is expected to fail.") instead of XCTAssert(false, "no exception")

2023-12-01 15:15 UTC, tib commented on Tests/FeatherMailTests/FeatherMailTests.swift
> +    func testExample() async throws {
Could we use a better name instead of example?

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTMailServiceBuilder.swift
> +        XCTMyMailService(config: config, availableSpace: 0)
We don't need availableSpace that comes from the storage service.

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTMailServiceContext.swift
> +    let isTestError: Bool
Please rename this to `throwTestError`: Bool.

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTMailServiceContext.swift
> +public struct XCTMyMailServiceContext: ServiceContext {
Maybe let's call this TestMailServiceContext?

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTMailServiceContext.swift
> +public struct XCTMyMailServiceContext: ServiceContext {
Also public modifier is unnecessary.

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTMailServiceBuilder.swift
> +struct XCTMyMailServiceBuilder: ServiceBuilder {
Let's rename this to TestMailServiceBuilder as well.

2023-12-01 15:15 UTC, tib commented on Tests/FeatherMailTests/MyMailServiceContext.swift
> +public struct MyMailServiceContext: ServiceContext {
This can be internal.

2023-12-01 15:15 UTC, tib commented on Tests/FeatherMailTests/MyMailService.swift
> +    var availableSpace: UInt64
We don't need this property at all.

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTMyMailService.swift
> +    var availableSpace: UInt64
We don't need this property.

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTMyMailService.swift
> +public enum XCTMailServiceError: Error {
Let's call this TestMailServiceError and make it internal.

2023-12-01 15:15 UTC, tib commented on Tests/XCTFeatherMailTests/XCTMyMailService.swift
> +struct XCTMyMailService: MailService {
This should be TestMailService.

2023-12-01 15:24 UTC, mzpx commented on Tests/FeatherMailTests/FeatherMailTests.swift
> +    func testExample() async throws {
I fixed that

2023-12-04 10:06 UTC, mzpx commented on Tests/XCTFeatherMailTests/XCTFeatherMailTests.swift
> +            XCTAssert(false, "no exception")
I fixed it :) My first test fix by heart :) I hope github can handled it :D

2023-12-04 21:44 UTC, tib approved these changes

2023-12-04 21:58 UTC, merged